version: "3.8"  # Ensure compatibility with service_healthy

services:
  web:
    build: .
    container_name: equipment_service
    networks:
      - my_network
    ports:
      - "8006:8000"
    depends_on:
      db:
        condition: service_healthy  # Ensures DB is ready before starting web
    environment:
      DJANGO_SETTINGS_MODULE: equipment_service.settings
      DATABASE_NAME: equipment_db
      DATABASE_USER: thamer
      DATABASE_PASSWORD: thamer4a
      DATABASE_HOST: db
      DATABASE_PORT: 5432  # Ensure Django connects to PostgreSQL correctly
    volumes:
      - .:/app
    restart: always

  db:
    image: postgres:13
    container_name: postgres-equipment
    networks:
      - my_network
    ports:
      - "5433:5432"  # Host maps 5433 to 5432 inside the container
    environment:
      POSTGRES_DB: equipment_db
      POSTGRES_USER: thamer
      POSTGRES_PASSWORD: thamer4a
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U thamer -d equipment_db"]
      interval: 10s
      retries: 5
      start_period: 10s

networks:
  my_network:

volumes:
  postgres_data:
