# Generated by Django 4.2.16 on 2025-04-24 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SiteStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_visitors', models.PositiveIntegerField(default=0)),
                ('total_page_views', models.PositiveIntegerField(default=0)),
                ('total_rentals', models.PositiveIntegerField(default=0)),
                ('total_revenue', models.FloatField(default=0)),
                ('avg_order_value', models.FloatField(default=0)),
                ('conversion_rate', models.FloatField(default=0)),
            ],
            options={
                'verbose_name': 'Site Statistics',
                'verbose_name_plural': 'Site Statistics',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='StuffManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('last_maintenance', models.DateField(blank=True, null=True)),
                ('condition', models.CharField(default='open', max_length=50)),
                ('rental_location', models.CharField(default='nabeul', max_length=255)),
                ('deposit', models.FloatField(blank=True, null=True)),
                ('availability', models.CharField(blank=True, max_length=255, null=True)),
                ('rental_zone', models.CharField(blank=True, max_length=255, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_required', models.FileField(blank=True, null=True, upload_to='contracts/')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('ip_address', models.CharField(max_length=45)),
                ('user_agent', models.TextField()),
                ('first_visit', models.DateTimeField(auto_now_add=True)),
                ('last_visit', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrafficSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('source', models.CharField(choices=[('organic', 'Organic Search'), ('direct', 'Direct'), ('social', 'Social Media'), ('email', 'Email'), ('referral', 'Referral'), ('paid', 'Paid Ads')], max_length=20)),
                ('visitors', models.PositiveIntegerField(default=0)),
                ('rentals', models.PositiveIntegerField(default=0)),
                ('revenue', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-date', 'source'],
                'unique_together': {('date', 'source')},
            },
        ),
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategory', to='equipments.category')),
            ],
        ),
        migrations.CreateModel(
            name='Stuff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stuffname', models.CharField(max_length=100)),
                ('short_description', models.CharField(default='open', max_length=100)),
                ('state', models.CharField(default='open', max_length=50)),
                ('rental_location', models.CharField(default='nabeul', max_length=255)),
                ('price_per_day', models.FloatField()),
                ('detailed_description', models.TextField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('brand', models.CharField(blank=True, max_length=255, null=True)),
                ('user', models.IntegerField(null=True)),
                ('created_at', models.DateField(auto_now_add=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stuffs', to='equipments.category')),
                ('stuff_management', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_stuffs', to='equipments.stuffmanagement')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.IntegerField()),
                ('rating', models.PositiveSmallIntegerField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='equipments.stuff')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('total_price', models.FloatField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment_method', models.CharField(blank=True, max_length=20, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('stuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.stuff')),
            ],
        ),
        migrations.CreateModel(
            name='ItemView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('organic', 'Organic Search'), ('direct', 'Direct'), ('social', 'Social Media'), ('email', 'Email'), ('referral', 'Referral'), ('paid', 'Paid Ads')], max_length=20)),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet')], max_length=10)),
                ('stuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.stuff')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.visitor')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.ImageField(upload_to='equipment_images/')),
                ('alt', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.PositiveIntegerField()),
                ('stuff', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipment_images', to='equipments.stuff')),
            ],
        ),
        migrations.CreateModel(
            name='DeviceStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('device_type', models.CharField(choices=[('desktop', 'Desktop'), ('mobile', 'Mobile'), ('tablet', 'Tablet')], max_length=10)),
                ('visitors', models.PositiveIntegerField(default=0)),
                ('rentals', models.PositiveIntegerField(default=0)),
                ('revenue', models.FloatField(default=0)),
            ],
            options={
                'ordering': ['-date', 'device_type'],
                'unique_together': {('date', 'device_type')},
            },
        ),
        migrations.CreateModel(
            name='CartActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('add', 'Add to Cart'), ('remove', 'Remove from Cart')], max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('stuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.stuff')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('views', models.PositiveIntegerField(default=0)),
                ('rentals', models.PositiveIntegerField(default=0)),
                ('revenue', models.FloatField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.category')),
            ],
            options={
                'ordering': ['-date', 'category'],
                'unique_together': {('date', 'category')},
            },
        ),
    ]
