# Generated by Django 4.2.16 on 2025-04-25 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('stuff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.stuff')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='equipments.visitor')),
            ],
        ),
    ]
