# Generated by Django 4.2.16 on 2025-05-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0002_favorite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stuff',
            name='user',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
