# Generated by Django 4.2.16 on 2025-05-20 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0003_alter_stuff_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='favorite',
            name='visitor',
        ),
        migrations.RemoveField(
            model_name='itemview',
            name='visitor',
        ),
        migrations.AddField(
            model_name='favorite',
            name='user',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='itemview',
            name='user',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
