# Generated by Django 4.2.16 on 2025-06-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0004_remove_favorite_visitor_remove_itemview_visitor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='customer',
            field=models.CharField(max_length=255),
        ),
    ]
