# Generated by Django 4.2.16 on 2025-06-18 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0005_alter_review_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='stuff',
            name='status',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
